server:
  port: 9002
spring:
  application:
    name: dolphin-wechat-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform?useSSL=false
    username: root
    password: P@ssw0rd
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  redis:
    host: ${redis}
    port: ${redis-port}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-addr}
    sentinel:
      transport:
        port: ${sentinel-port}
        dashboard: ${sentinel-dashboard}
  profiles:
    active: ${gok-env}

mybatis-plus:
  mapper-locations: classpath:mapper/*/*-mapper.xml
  type-aliases-package: cn.goktech.dolphin.upms.entity
  configuration:
    log-prefix: dao.
    map-underscore-to-camel-case: true

ignore:
  urls:
    - /actuator/**

feign:
  sentinel:
    enabled: true

#hystrix:
#  shareSecurityContext: true

# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000

# 防止第一次调用超时，使用eagerLoad模式
ribbon:
  eager-load:
    enabled: true
    clients: dolphin-upms-service
