server:
  port: 7400
  undertow:
    io-threads: 4
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true

spring:
  application:
    name: dolphin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: dolphin-upms-service
          uri: lb://dolphin-upms-service
          predicates:
            - Path=/uaa/sys/**
          filters:
            - StripPrefix=1
        - id: dolphin-auth-service
          uri: lb://dolphin-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: ${nacos-addr}
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

feign:
  sentinel:
    enabled: true

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000