server:
  port: 9001
spring:
  application:
    name: dolphin-upms-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dolphin-base?useSSL=false
    username: root
    password: P@ssw0rd
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  redis:
    host: ${redis}
    port: ${redis-port}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos}
  profiles:
    active: ${gok-env}

mybatis-plus:
  mapper-locations: classpath:mapper/*/*-mapper.xml
  type-aliases-package: cn.goktech.dolphin.upms.entity
  configuration:
    log-prefix: dao.
    map-underscore-to-camel-case: true


client:
  appid: app
  secret: app

ignore:
  urls:
    - /actuator/**
    - /demo/**
    - /inner/**
    - /sys/login
    - /sys/logout

feign:
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

seq:
  zkAddr: 192.168.2.218:2181
  distribute: false

# 防止第一次调用超时，使用eagerLoad模式
ribbon:
  eager-load:
    enabled: true
    clients: dolphin-auth-service